<?php
foreach($this->apps as $target => $modules):
    if(empty($modules)) {
        continue;
    }
    
    $require = array_merge(['angular'], array_map(function($item) {
        return 'module/' . $item;
    }, $modules));
    ?>
    <script>
        require(<?=json_encode($require)?>, function(angular) {
            <?php if($target === 'document'):?>
                angular.bootstrap(document.documentElement, <?=json_encode($modules)?>);
            <?php elseif($target === 'body'):?>
                angular.bootstrap(document.body, <?=json_encode($modules)?>);
            <?php else:?>
                angular.bootstrap(document.getElementById('<?=$target?>'), <?=json_encode($modules)?>);
            <?php endif?>
        });
    </script>
    <?php
endforeach;